export const animes = [
    {
        id: 1,
        name: 'One Piece',
        ep: 1100,
        img: './imgs/one piece.jpeg',
        rating: '⭐⭐⭐⭐⭐',
        review: 'Monkey D. Luffy sets sail across the Grand Line searching for the legendary treasure known as the One Piece. Along the journey he gathers a crew of powerful friends and faces dangerous pirates, marines, and mysterious islands. Their adventures test friendship, courage, and the meaning \nof true freedom.',
        url: "https://www.youtube.com/embed/8AUBIaLsmDQ?si=hrcOqn6GE5pBC46w",
        status: 'ongoing',
        released: 1999,
        genre: 'Adventure, Action',
        studio: 'Toei Animation',
        duration: '24 min'
    },

    {
        id: 2,
        name: 'Demon Slayer',
        ep: 63,
        img: './imgs/demon slayer.jpg',
        rating: '⭐⭐⭐⭐⭐',
        review: 'Tanjiro Kamado becomes a demon slayer after his family is slaughtered and his sister is turned into a demon. Determined to avenge his family, he trains tirelessly and joins the Demon Slayer Corps. Along the way he faces terrifying demons and forms deep bonds with fellow warriors.',
        url: 'https://www.youtube.com/embed/x7uLutVRBfI?si=00YF1HLYJv1tGpqp',
        status: 'completed',
        released: 2019,
        genre: 'Action, Supernatural, Adventure',
        studio: 'ufotable',
        duration: '24 min'
    },

    {
        id: 3,
        name: 'Solo Leveling',
        ep: 24,
        img: './imgs/solo.jpg',
        rating: '⭐⭐⭐⭐⭐',
        review: 'Sung Jin-Woo begins as the weakest hunter in a dangerous world filled with monsters and dungeons. After a mysterious incident he gains the unique ability to level up endlessly. With every battle he grows stronger and rises toward becoming humanity’s most powerful hunter.',
        url: "https://www.youtube.com/embed/IrHTT2IEKpE?si=Xg930kFjD3jLFXu3",
        status: 'ongoing',
        released: 2024,
        genre: 'Action, Fantasy, Adventure',
        studio: 'A-1 Pictures',
        duration: '24 min'
    },
    {
        id: 4,
        name: 'Jujutsu Kaisen',
        ep: 24,
        img: './imgs/jjk.jpg',
        rating: '⭐⭐⭐⭐⭐',
        review: 'Yuji Itadori accidentally swallows a powerful cursed object and becomes the host of a dangerous spirit. He joins the Jujutsu Sorcerers to battle curses that threaten humanity. Together they face deadly enemies and uncover dark secrets within the world of sorcery.',
        url: "https://www.youtube.com/embed/bF_pxKpL6Xk?si=plwWr8Pijv3k4IY2",
        status: 'ongoing',
        released: 2020,
        genre: 'Action, Supernatural',
        studio: 'MAPPA',
        duration: '24 min'
    },
    {
        id: 5,
        name: 'Hells Paradise',
        ep: 12,
        img: './imgs/hell.jpg',
        rating: '⭐⭐⭐⭐',
        review: 'Gabimaru the Hollow is sent to a mysterious island filled with deadly creatures and immortal beings. Alongside other criminals he searches for the legendary elixir of life to earn his freedom. Survival demands strength, trust, and confronting terrifying horrors.',
        url: "https://www.youtube.com/embed/whFAGQSDyTg?si=QdOR7L_T5jGlQ_cF",
        status: 'ongoing',
        released: 2023,
        genre: 'Action, Horror, Supernatural',
        studio: 'MAPPA',
        duration: '24 min'
    },
    {
        id: 6,
        name: 'Attack on Titan',
        ep: 87,
        img: './imgs/aot.jpg',
        rating: '⭐⭐⭐⭐⭐',
        review: 'Eren Yeager witnesses the destruction of his home by massive Titans that threaten humanity. Driven by rage and grief, he vows to eliminate every Titan. As the story unfolds, shocking truths about the world and humanity come to light.',
        url: "https://www.youtube.com/embed/u1uWW_p5xjE?si=jL6XfJ__J56TchWb",
        status: 'completed',
        released: 2013,
        genre: 'Action, Dark Fantasy',
        studio: 'Wit Studio',
        duration: '24 min'
    },
    {
        id: 7,
        name: 'Naruto Shippuden',
        ep: 500,
        img: './imgs/naruto.jpg',
        rating: '⭐⭐⭐⭐⭐',
        review: 'Naruto Uzumaki returns stronger after years of training and determination. He battles powerful enemies and dangerous organizations threatening the ninja world. Throughout the journey he never gives up on his dream of becoming Hokage.',
        url: "https://www.youtube.com/embed/Q8ilG9qgBlc?si=Yc8TSbumHmV7moxD",
        status: 'completed',
        released: 2007,
        genre: 'Adventure, Action, Ninja',
        studio: 'Pierrot',
        duration: '24 min'
    },
    {
        id: 8,
        name: 'Black Clover',
        ep: 170,
        img: './imgs/black.jpg',
        rating: '⭐⭐⭐⭐',
        review: 'Asta and Yuno grow up together in a world where magic determines power and status. Despite having no magic, Asta refuses to give up on his dream. With determination and hard training he aims to become the Wizard King.',
        url: "https://www.youtube.com/embed/WcBw8NS5t08?si=xGpQFhDl0X_FXqg5",
        status: 'completed',
        released: 2017,
        genre: 'Action, Adventure, Fantasy',
        studio: 'Studio Pierrot',
        duration: '24 min'
    },
    {
        id: 9,
        name: 'Dandadan',
        ep: 12,
        img: './imgs/dan.jpg',
        rating: '⭐⭐⭐⭐',
        review: 'Two high school students get entangled in bizarre events involving aliens and supernatural spirits. Their lives turn chaotic as strange powers and mysteries appear. Action, comedy, and unexpected friendships drive their wild adventure.',
        url: "https://www.youtube.com/embed/iiwOVqGtZj4?si=n9wPMYG3tYpOEWqJ",
        status: 'ongoing',
        released: 2023,
        genre: 'Action, Comedy, Supernatural',
        studio: 'J.C. Staff',
        duration: '24 min'
    },
    {
        id: 10,
        name: 'Scissor 7',
        ep: 42,
        img: './imgs/scissor.jpg',
        rating: '⭐⭐⭐⭐',
        review: 'Seven is an amnesiac barber who secretly works as an assassin for hire. His missions often spiral into hilarious and chaotic situations. Between battles he tries to live peacefully while uncovering his mysterious past.',
        url: "https://www.youtube.com/embed/inamzXsjq8c?si=8VYZtppm0JfW-kfs",
        status: 'ongoing',
        released: 2020,
        genre: 'Action, Comedy, Martial Arts',
        studio: 'Bilibili',
        duration: '15 min'
    },
    {
        id: 11,
        name: 'Chainsaw Man',
        ep: 12,
        img: './imgs/chain.jpg',
        rating: '⭐⭐⭐⭐⭐',
        review: 'Denji lives in poverty until he merges with his pet devil Pochita. The transformation grants him chainsaw powers to hunt dangerous devils. While fighting brutal battles, he searches for a simple and meaningful life.',
        url: "https://www.youtube.com/embed/j9sSzNmB5po?si=018vrYmaeOtGkymw",
        status: 'ongoing',
        released: 2022,
        genre: 'Action, Horror, Supernatural',
        studio: 'MAPPA',
        duration: '24 min'
    },
    {
        id: 12,
        name: 'Vinland Saga',
        ep: 24,
        img: './imgs/vinland.jpg',
        rating: '⭐⭐⭐⭐',
        review: 'Thorfinn grows up in a brutal Viking era driven by revenge against his father’s killer. The journey exposes him to war, loyalty, and betrayal. Over time he questions violence and searches for a deeper meaning in life.',
        url: "https://www.youtube.com/embed/SDX42x8p_lI?si=uuGYexxQbDblruFr",
        status: 'completed',
        released: 2019,
        genre: 'Action, Historical, Adventure',
        studio: 'Wit Studio',
        duration: '24 min'
    },
    {
        id: 13,
        name: 'God of High School',
        ep: 13,
        img: './imgs/god.jpg',
        rating: '⭐⭐⭐⭐⭐',
        review: 'Jin Mori joins an intense martial arts tournament filled with powerful fighters. Competitors use mysterious borrowed powers during explosive battles. As the competition continues, hidden conspiracies begin to emerge.',
        url: "https://www.youtube.com/embed/cf04-m6wotQ?si=vrRiKaBmCd1gqa8n",
        status: 'completed',
        released: 2020,
        genre: 'Action, Martial Arts, Supernatural',
        studio: 'MAPPA',
        duration: '24 min'
    },
    {
        id: 14,
        name: 'Tokyo Revengers',
        ep: 24,
        img: './imgs/tokyo.jpg',
        rating: '⭐⭐⭐⭐⭐',
        review: 'Takemichi discovers he can travel back in time to his middle school days. He tries to change tragic events and save the people he loves. His journey pulls him into the dangerous world of delinquent gangs.',
        url: "https://www.youtube.com/embed/Q7u676SjiBE?si=Okz5AjITExHet-pv",
        status: 'ongoing',
        released: 2021,
        genre: 'Action, Drama, Supernatural',
        studio: 'LIDENFILMS',
        duration: '24 min'
    },

    {
        id: 15,
        name: 'Fullmetal Alchemist',
        ep: 64,
        img: './imgs/full.jpg',
        rating: '⭐⭐⭐⭐⭐',
        review: 'Edward and Alphonse Elric attempt forbidden alchemy and pay a terrible price. They search for the Philosopher’s Stone to restore their bodies. Their journey reveals deep political conspiracies and the cost of ambition.',
        url: "https://www.youtube.com/embed/-GoNo0DGroU?si=LbBCLUfIjlD-EfKH",
        status: 'completed',
        released: 2003,
        genre: 'Action, Adventure, Fantasy',
        studio: 'Bones',
        duration: '24 min'
    },

    {
        id: 16,
        name: 'Dororo',
        ep: 24,
        img: './imgs/dororo.jpg',
        rating: '⭐⭐⭐⭐',
        review: 'Hyakkimaru was born without body parts due to a demonic pact made by his father. He journeys across the land defeating demons to reclaim what was stolen. Along the way he forms an unlikely friendship with the thief Dororo.',
        url: "https://www.youtube.com/embed/kiW3Ib8Dw0I?si=pdnXpOsYGu6zMbHP",
        status: 'completed',
        released: 2019,
        genre: 'Action, Adventure, Supernatural',
        studio: 'Mappa, Tezuka Productions',
        duration: '24 min'
    },

    {
        id: 17,
        name: 'Akame ga Kill',
        ep: 24,
        img: './imgs/akagame.jpg',
        rating: '⭐⭐⭐⭐',
        review: 'Tatsumi joins a secret group of assassins fighting against a corrupt empire. Each mission brings dangerous enemies and moral struggles. The story shows the harsh reality of war and sacrifice.',
        url: "https://www.youtube.com/embed/sCGWxQuSoDU?si=Z7MDlx0YoL1geIl7",
        status: 'completed',
        released: 2014,
        genre: 'Action, Fantasy, Drama',
        studio: 'White Fox',
        duration: '24 min'
    },

    {
        id: 18,
        name: 'Hunter x Hunter',
        ep: 148,
        img: './imgs/hunter.jpg',
        rating: '⭐⭐⭐⭐⭐',
        review: 'Gon Freecss dreams of becoming a Hunter like his legendary father. He faces dangerous exams and powerful opponents. Along the way he builds strong friendships and experiences unforgettable adventures.',
        url: "https://www.youtube.com/embed/zA6WNlpFyvE?si=dTQD_UAKf-RHVM6M",
        status: 'ongoing',
        released: 2011,
        genre: 'Adventure, Action, Fantasy',
        studio: 'Madhouse',
        duration: '24 min'
    },

    {
        id: 19,
        name: 'Death Note',
        ep: 37,
        img: './imgs/death.jpg',
        rating: '⭐⭐⭐⭐⭐',
        review: 'Light Yagami finds a mysterious notebook that can kill anyone whose name is written inside. He begins reshaping the world according to his sense of justice. A genius detective known as L rises to challenge him in a deadly battle of intellect.',
        url: "https://www.youtube.com/embed/SRqijryA7ok?si=vXi8r_EJOdNZXazw",
        status: 'completed',
        released: 2006,
        genre: 'Mystery, Supernatural, Thriller',
        studio: 'Madhouse',
        duration: '24 min'
    },

    {
        id: 20,
        name: 'Baki',
        ep: 26,
        img: './imgs/baki.jpg',
        rating: '⭐⭐⭐⭐',
        review: 'Baki Hanma trains relentlessly to become the strongest fighter alive. His ultimate goal is to surpass his legendary father. Each battle pushes his limits in brutal martial arts combat.',
        url: "https://www.youtube.com/embed/kascCjqCoJE?si=OuYPSGFifDK9hfaB",
        status: 'ongoing',
        released: 2020,
        genre: 'Action, Martial Arts',
        studio: 'TMS Entertainment',
        duration: '24 min'
    },

    {
        id: 21,
        name: 'Windbreaker',
        ep: 12,
        img: './imgs/wind.jpg',
        rating: '⭐⭐⭐⭐',
        review: 'A determined cyclist joins a competitive high school racing team. Together they face intense rivalries and demanding training. Their shared passion drives them toward victory and personal growth.',
        url: "https://www.youtube.com/embed/Y0S3Qcnmw-4?si=BpAuzid_RRDuzVN0",
        status: 'ongoing',
        released: 2023,
        genre: 'Sports, Drama',
        studio: 'Studio XYZ',
        duration: '24 min'
    },

    {
        id: 22,
        name: 'A Silent Voice',
        ep: 1,
        img: './imgs/voice.jpg',
        rating: '⭐⭐⭐⭐⭐',
        review: 'Shoya seeks redemption after bullying a deaf girl named Shoko in elementary school. Years later he tries to reconnect and make amends. The story explores forgiveness, empathy, and emotional healing.',
        url: "https://www.youtube.com/embed/nfK6UgLra7g?si=8dwSxIFzEH_WHMuA",
        status: 'completed',
        released: 2016,
        genre: 'Drama, Romance, School',
        studio: 'Kyoto Animation',
        duration: '129 min'
    },

    {
        id: 23,
        name: 'Your Name',
        ep: 1,
        img: './imgs/name.jpg',
        rating: '⭐⭐⭐⭐⭐',
        review: 'Two teenagers mysteriously begin swapping bodies despite living in different places. Their connection grows as they learn about each other’s lives. Together they race against time to prevent a looming disaster.',
        url: "https://www.youtube.com/embed/xU47nhruN-Q?si=mhxBfMkE2VxTGne6",
        status: 'completed',
        released: 2016,
        genre: 'Romance, Supernatural, Drama',
        studio: 'CoMix Wave Films',
        duration: '106 min'
    },

    {
        id: 24,
        name: '5 Centimeters per Second',
        ep: 1,
        img: './imgs/second.jpg',
        rating: '⭐⭐⭐⭐',
        review: 'Takaki and Akari share a deep childhood bond that distance slowly challenges. As years pass their lives drift in different directions. The story reflects on love, time, and missed connections.',
        url: "https://www.youtube.com/embed/WfUkwBnEWpU?si=zR-ZqzFFiJDVUH9i",
        status: 'completed',
        released: 2007,
        genre: 'Romance, Drama, Slice of Life',
        studio: 'CoMix Wave Films',
        duration: '63 min'
    },

    {
        id: 25,
        name: 'Suzume',
        ep: 1,
        img: './imgs/suzume.jpg',
        rating: '⭐⭐⭐⭐',
        review: 'Suzume encounters mysterious doors that unleash disasters across Japan. She travels the country to close them before catastrophe strikes. Along the way she discovers courage, friendship, and her past.',
        url: "https://www.youtube.com/embed/g0JMPkn7Wuo?si=xYFzbHI6gfKQWIYE",
        status: 'completed',
        released: 2022,
        genre: 'Adventure, Fantasy, Drama',
        studio: 'CoMix Wave Films',
        duration: '120 min'
    },

    {
        id: 26,
        name: 'Tunnel to Summer',
        ep: 1,
        img: './imgs/summer.jpg',
        rating: '⭐⭐⭐⭐',
        review: 'Two teenagers discover a mysterious tunnel rumored to grant wishes. The deeper they explore, the more time they lose in the real world. Their journey becomes a story about youth, choices, and sacrifice.',
        url: "https://www.youtube.com/embed/quNGzBv9arI?si=DrsAAg12rElu-6pl",
        status: 'completed',
        released: 2023,
        genre: 'Drama, Slice of Life, Romance',
        studio: 'Studio ABC',
        duration: '90 min'
    },

    {
        id: 27,
        name: 'You Are Lie in April',
        ep: 22,
        img: './imgs/april.jpg',
        rating: '⭐⭐⭐⭐⭐',
        review: 'A piano prodigy loses his passion for music after a tragic event. Everything changes when he meets a lively violinist named Kaori. Her spirit inspires him to rediscover music and life again.',
        url: "https://www.youtube.com/embed/3aL0gDZtFbE?si=bAYUGrrLlTlmpvnH",
        status: 'completed',
        released: 2014,
        genre: 'Drama, Romance, Music',
        studio: 'A-1 Pictures',
        duration: '22 min'
    },

    {
        id: 28,
        name: 'I Want to Eat Your Pancreas',
        ep: 1,
        img: './imgs/pancreas.jpg',
        rating: '⭐⭐⭐⭐⭐',
        review: 'A quiet boy learns that his cheerful classmate Sakura is secretly terminally ill. They begin spending time together and sharing unforgettable experiences. Their friendship becomes a touching journey about life and loss.',
        url: "https://www.youtube.com/embed/MmoBvmJA9XI?si=nAXwGTXDk8bF3RVt",
        status: 'completed',
        released: 2018,
        genre: 'Drama, Romance, School',
        studio: 'Studio VOLN',
        duration: '108 min'
    },

    {
        id: 29,
        name: 'Erased',
        ep: 12,
        img: './imgs/erased.jpg',
        rating: '⭐⭐⭐⭐⭐',
        review: 'Satoru suddenly gains the ability to travel back in time to prevent tragedies. He returns to his childhood to stop a series of kidnappings. Solving the mystery could save lives and change fate forever.',
        url: "https://www.youtube.com/embed/DwmxEAWjTQQ?si=D89l8TTdlY6hDKtH",
        status: 'completed',
        released: 2016,
        genre: 'Mystery, Thriller, Supernatural',
        studio: 'A-1 Pictures',
        duration: '24 min'
    },

    {
        id: 30,
        name: 'Garden of Words',
        ep: 1,
        img: './imgs/words.jpg',
        rating: '⭐⭐⭐⭐',
        review: 'A student skips school on rainy mornings and meets a mysterious woman in a quiet garden. Their chance meetings slowly build a unique bond. The story gently explores loneliness, dreams, and connection.',
        url: "https://www.youtube.com/embed/udDIkl6z8X0?si=z_UiHnr1cljnkSYx",
        status: 'completed',
        released: 2013,
        genre: 'Drama, Romance, Slice of Life',
        studio: 'CoMix Wave Films',
        duration: '46 min'
    },

    {
        id: 31,
        name: 'Weathering With You',
        ep: 1,
        img: './imgs/weather.jpg',
        rating: '⭐⭐⭐⭐⭐',
        review: 'A runaway boy meets a girl who has the power to control the weather. Together they help people by bringing sunshine to rainy Tokyo. Their bond grows while supernatural consequences begin to appear.',
        url: "https://www.youtube.com/embed/Q6iK6DjV_iE?si=cUm883Ul2OphdZEn",
        status: 'completed',
        released: 2019,
        genre: 'Romance, Fantasy, Drama',
        studio: 'CoMix Wave Films',
        duration: '112 min'
    },

    {
        id: 32,
        name: 'Howls Moving Castle',
        ep: 1,
        img: './imgs/castle.jpg',
        rating: '⭐⭐⭐⭐⭐',
        review: 'Sophie is cursed by a witch and transformed into an old woman. She finds refuge in the magical moving castle of the wizard Howl. Their journey reveals courage, love, and the power of kindness.',
        url: "https://www.youtube.com/embed/ARCQf2CEr8k?si=0QP6oi31HxNdrEmK",
        status: 'completed',
        released: 2004,
        genre: 'Fantasy, Romance, Adventure',
        studio: 'Studio Ghibli',
        duration: '119 min'
    },

    {
        id: 33,
        name: 'Summer Ghost',
        ep: 1,
        img: './imgs/ghost.jpg',
        rating: '⭐⭐⭐⭐',
        review: 'Three teenagers search for a ghost rumored to appear during summer nights. Meeting the spirit changes their perspectives on life. The short story reflects on dreams, regrets, and moving forward.',
        url: "https://www.youtube.com/embed/JgXXExMU9IQ?si=q68Si3DtYjQd3qyj",
        status: 'completed',
        released: 2021,
        genre: 'Drama, Supernatural, Slice of Life',
        studio: 'LIDENFILMS',
        duration: '25 min'
    },

    {
        id: 34,
        name: 'Frieren',
        ep: 12,
        img: './imgs/frieren.jpg',
        rating: '⭐⭐⭐⭐',
        review: 'After defeating the demon king, the elf mage Frieren continues her long life. She reflects on friendships that were brief compared to her lifespan. Her journey becomes a search for meaning and human connection.',
        url: "https://www.youtube.com/embed/EOMVXqH9DSg?si=TH5zE1RrwCL-Hp32",
        status: 'ongoing',
        released: 2023,
        genre: 'Fantasy, Adventure, Drama',
        studio: 'Studio XYZ',
        duration: '24 min'
    },

    {
        id: 35,
        name: 'Fire Force',
        ep: 48,
        img: './imgs/force.jpg',
        rating: '⭐⭐⭐⭐',
        review: 'Shinra Kusakabe joins the Fire Force to fight people who spontaneously combust into monsters. Each mission reveals more about the mysterious phenomenon. The team uncovers dark secrets behind the flames.',
        url: "https://www.youtube.com/embed/voLZJvdwUEE?si=LuesT3Gy9kbqvBxt",
        status: 'completed',
        released: 2019,
        genre: 'Action, Supernatural, Fantasy',
        studio: 'David Production',
        duration: '24 min'
    },

    {
        id: 36,
        name: 'Bleach',
        ep: 366,
        img: './imgs/blood.jpg',
        rating: '⭐⭐⭐⭐⭐',
        review: 'Ichigo Kurosaki gains the powers of a Soul Reaper and begins protecting humans from evil spirits. He battles powerful enemies while guiding lost souls to the afterlife. His journey leads to intense battles and deep character growth.',
        url: "https://www.youtube.com/embed/fmWc9lWcuGc?si=OfSD679j5j9tHTFz",
        status: 'completed',
        released: 2004,
        genre: 'Action, Supernatural, Shonen',
        studio: 'Studio Pierrot',
        duration: '24 min'
    },

    {
        id: 37,
        name: 'Mushoku Tensei',
        ep: 48,
        img: './imgs/tensei.jpg',
        rating: '⭐⭐⭐⭐',
        review: 'A man is reincarnated into a magical world as Rudeus Greyrat. Determined to live without regrets, he studies magic and adventure. His new life becomes a journey of growth, relationships, and redemption.',
        url: "https://www.youtube.com/embed/M-3YqJA6UlM?si=fVG_couHnFfoEk-k",
        status: 'ongoing',
        released: 2021,
        genre: 'Fantasy, Isekai, Adventure',
        studio: 'Studio Bind',
        duration: '24 min'
    },

    {
        id: 38,
        name: 'Re:Zero',
        ep: 25,
        img: './imgs/rezero.jpg',
        rating: '⭐⭐⭐⭐⭐',
        review: 'Subaru Natsuki suddenly finds himself transported to a fantasy world. He discovers that dying sends him back to a previous checkpoint. Using this painful ability, he struggles to save the people he cares about.',
        url: "https://www.youtube.com/embed/5XjMOv28Xxc?si=hOBUhOe14NHvTlOZ",
        status: 'ongoing',
        released: 2020,
        genre: 'Fantasy, Isekai, Drama',
        studio: 'White Fox',
        duration: '24 min'
    }
];